#!/usr/bin/env bash
# Prints out numbers from 1 to 100 but prints; Fizz for multiples of 3, Buzz for multiples of 5 and FizzBuzz for multiples of 3 and 5

i=1
while [ "$i" -le 100 ]
do
	echo "$i"
done
